server:
  port: 8081

spring:
  application:
    name: customer
  datasource:
    #url: jdbc:mysql://${MYSQL_HOST:172.19.0.3}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:microservice_customer_db}?autoReconnect=true&useSSL=false
    url: jdbc:mysql://mariadb:3306/microservice_customer_db
    username: ${MYSQL_USER:admin}
    password: ${MYSQL_PASSWORD:password}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka_url:http://eureka-server:8761/eureka/}
  management:
    tracing:
      sampling:
        probability: 1.0
