services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_USER:  admin
      MYSQL_PASSWORD: password
    expose:
      - "40000"
    ports:
      - "40000:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      db:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "40001"
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:
      db:
        #- ipv4_address: 172.18.0.2

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  eureka-server:
    image: maxdoc2023/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin

  api-gateway:
    image: maxdoc2023/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server

  customer:
    image: maxdoc2023/customer:latest
    container_name: customer
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - db
    depends_on:
      - zipkin
      - eureka-server
      - mariadb
      - rabbitmq

  fraud:
    image: maxdoc2023/fraud:latest
    container_name: fraud
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - db
    depends_on:
      - zipkin
      - eureka-server
      - mariadb
      - rabbitmq

  notification:
    image: maxdoc2023/notification:latest
    container_name: notification
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - db
    depends_on:
      - zipkin
      - eureka-server
      - mariadb
      - rabbitmq

volumes:
  mariadb:
    driver: local

networks:
  db:
    driver: bridge
  spring:
    driver: bridge

