server:
  port: 8083

spring:
  application:
    name: notification
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:172.19.0.2}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:microservice_notification_db}?autoReconnect=true&useSSL=false
    username: ${MYSQL_USER:admin}
    password: ${MYSQL_PASSWORD:password}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka/}

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key